version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car_sale_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_api_network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=alifarid0011@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      web_api_network:
    depends_on:
     - postgres
    ports:
      - 5050:80

  redis:
    image: redis
    restart: unless-stopped
    command: ["redis-server","/etc/redis/redis.conf"]

    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    networks:
     web_api_network:

volumes:
    postgres_data:
    pgadmin_data:
    redis_data:
    logs:


networks:
  web_api_network:
    driver: bridge
